imports:
    - { resource: parameters.yml }
    - { resource: phpcr.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        name: 'ecommerce'
    fragments:       ~
    http_method_override: true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'


assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

doctrine_phpcr:
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    odm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        locales:
            en:
                - de
                - fr
            de:
                - en
                - fr
            fr:
                - en
                - de

#liip_doctrine_cache:
#    namespaces:
#        meta:
#            type: file_system
#        nodes:
#            type: file_system

fos_rest:
    view:
        view_response_listener: force
        formats:
            json: true
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    format_listener:
        default_priorities:
            - html
            - json
            - "*/*"
    serializer:
        serialize_null: true

jms_serializer:
    metadata:
        directories:
            Jackalope:
                namespace_prefix: "Jackalope"
                path: "%kernel.root_dir%/Resources/serializer/Jackalope"

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
