sandbox_main:
    resource: "@SandboxMainBundle/Resources/config/routing.xml"
    prefix:   /

ecommerce_core:
    resource: "@EcommerceCoreBundle/Resources/config/routing.xml"
    prefix:   /core


login_check:
    pattern:   /login_check
    options: { i18n: false }

logout:
    pattern:   /logout
    options: { i18n: false }
